name: at_tension
favicon: null
layout_spectrum: 0.36303
typography_spectrum: 0.92263
title: at_tension
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191b1a'
    - '#0cc672'
    - '#0ea55e'
    - '#00ff9f'
    - '#0b512c'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
